import type { Metadata } from "next"
import { ThemeProvider } from "@/context/ThemeContext"
import Footer from "@/components/Footer"
import "./globals.css"
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <ThemeProvider>
          <div className="bg-bg-primary dark:bg-dark-bg-primary">
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
